services:
  mysqlSiege:
    image: mysql:latest
    container_name: archi-bd-siege
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 45s
    env_file:
      - bd.env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./bd/mysqlSiege:/var/lib/mysql

  mysqlMagasin:
    image: mysql:latest
    container_name: archi-bd-magasin
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 45s
    env_file:
      - bd.env
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./bd/mysqlMagasin:/var/lib/mysql

  bdcreation:
    build: ./bd/bdinit
    container_name: bd-creation
    restart: no
    depends_on:
      mysqlSiege:
        condition: service_healthy

  bdinit_magasin:
    build: ./bd/bdinit_magasin/
    container_name: bd-init-magasin
    restart: no
    depends_on:
      mysqlMagasin:
        condition: service_healthy
      mysqlSiege:
        condition: service_healthy
      bdcreation:
        condition: service_completed_successfully

  rmi:
    build: ./rmi/
    container_name: rmi_server
    restart: always
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9090"]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 30s

  magasin_server:
    build: ./servers/server_client/client/
    container_name: magasin_server
    restart: no
    ports:
      - "1099:1099"
    depends_on:
      rmi:
        condition: service_healthy
      mysqlMagasin:
        condition: service_healthy
      bdcreation:
        condition: service_completed_successfully
