services:
  mysqlSiege:
    image: mysql:latest
    container_name: archi-bd-siege
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 45s
    env_file:
      - bd.env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./bd/mysqlSiege:/var/lib/mysql

  mysqlMagasin:
    image: mysql:latest
    container_name: archi-bd-magasin
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 45s
    env_file:
      - bd.env
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./bd/mysqlMagasin:/var/lib/mysql

  bdcreation:
    build: ./bd/bdinit
    container_name: bd-creation
    restart: no
    depends_on:
      mysqlSiege:
        condition: service_healthy

  bdinit_magasin:
    build: ./bd/bdinit_magasin/
    container_name: bd-init-magasin
    restart: no
    depends_on:
      mysqlMagasin:
        condition: service_healthy
      mysqlSiege:
        condition: service_healthy
      bdcreation:
        condition: service_completed_successfully

  magasin_server:
    build: ./servers/server_client/client/
    container_name: magasin_server
    restart: no
    ports:
      - "1099:1099"
    depends_on:
      mysqlMagasin:
        condition: service_healthy
      bdcreation:
        condition: service_completed_successfully
      siege_server:
        condition: service_healthy

  siege_server:
    build: ./servers/server_siege/
    container_name: siege_server
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 1099 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "1100:1099"
    depends_on:
      mysqlSiege:
        condition: service_healthy
      bdcreation:
        condition: service_completed_successfully
