# Utilise une image légère avec Java pré-installé
FROM eclipse-temurin:17-jre-alpine

# Définit le répertoire de travail
WORKDIR /app

# Expose le port du registre RMI (9090 dans ton cas)
# Note : RMI utilise souvent un deuxième port dynamique pour les objets, 
# mais commençons par le registre.
EXPOSE 9090

# Commande par défaut pour lancer le registre
# On utilise l'exécutable fourni par le JRE
ENTRYPOINT [ "rmiregistry", "9090" ]