FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /app

COPY ./bdinit/pom.xml .
COPY ./bdinit/src ./src

RUN mvn clean package -DskipTests
RUN ls target/

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=build /app/target/*jar-with-dependencies.jar app.jar

ENTRYPOINT [ "java", "-jar", "app.jar" ]